version: "3"
services:
  backend:
    build: .
    image: covid19_backend:1.0
    environment:
      - DB_HOST=db
    ports:
      - "7001:7001"
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data:
  